---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: node-exporter
spec:
  staticConfigs:
    - targets:
        - nas.main.internal:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: node-exporter
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: smartctl-exporter
spec:
  staticConfigs:
    - targets:
        - nas.main.internal:9633
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: smartctl-exporter
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: nut-exporter
spec:
  staticConfigs:
    - targets:
        - nas.main.internal:9199
      labels:
          ups:  "primary"
  metricsPath: /ups_metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: nut-exporter
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: doco-cd-exporter
spec:
  staticConfigs:
    - targets:
        - nas.main.internal:9130
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job

      replacement: doco-cd-exporter
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: liquidctl-exporter
spec:
  staticConfigs:
    - targets:
        - nas.main.internal:9530
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: liquidctl-exporter
