---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: iot
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "iot",
      "plugins": [
        {
          "type": "macvlan",
          "master": "br0.20",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "addresses": [
              {
                "address": "10.10.20.240/24",
                "gateway": "10.10.20.254"
              }
            ],
            "routes": [
              { "dst": "10.10.20.0/24" },
              { "dst": "239.255.255.250/32" }
            ]
          }
        },
        { "type": "sbr" },
        {
          "type": "tuning",
          "allmulti": true,
          "sysctl": {
            "net.ipv4.conf.all.rp_filter": "2",
            "net.ipv4.conf.net1.rp_filter": "2"
          }
        }
      ]
    }
