---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: media
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "media",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.40",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "10.10.40.0/24", "gw": "10.10.40.254" }
            ]
          }
        }
      ]
    }
