---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backendtrafficpolicy.yaml
  - ./clienttrafficpolicy.yaml
  - ./externalservices.yaml
  - ./envoypatchpolicy.yaml
  - ./envoyproxy.yaml
  - ./gateway.yaml
  - ./httproute.yaml