services:
  webtop:
    image: lscr.io/linuxserver/webtop:debian-xfce@sha256:acd33328153ac1c6e22cf1a48ff500252ac2b568c4ae6f994c8707649ebc9476
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TITLE=F9 Remote
      - DRINODE=/dev/dri/renderD128
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - /mnt/apps-pool/appdata/webtop/config:/config
      - ./resources:/custom-cont-init.d:ro
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb" #optional
    restart: unless-stopped
