services:
  webtop:
    image: lscr.io/linuxserver/webtop:debian-xfce@sha256:1b9dc97e69b3001d7a680cc5ab9062bb9165287624da36ea491b0da10f8d9450
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TITLE=F9 Remote
      - DRINODE=/dev/dri/renderD128
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - /mnt/apps-pool/appdata/webtop/config:/config
      - ./resources:/custom-cont-init.d:ro
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb" #optional
    restart: unless-stopped
