api:
  listen: :80
  origin: "*"
rtsp:
  listen: :554
webrtc:
  listen: :8555
  candidates:
    - 10.10.100.204:8555
    - stun:8555
  ice_servers:
    - urls:
        - stun:stun.cloudflare.com:3478
streams:
  doorbell:
    - ${DOORBELL}
#    - ffmpeg:doorbell#audio=opus
  front_camera:
    - ${FRONT_CAMERA}
#    - ffmpeg:front_camera#audio=opus
  back_camera:
    - ${BACK_CAMERA}
#    - ffmpeg:back_camera#audio=opus
  side_camera:
    - ${SIDE_CAMERA}
#    - ffmpeg:side_camera#audio=opus