# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
- ./authelia/ks.yaml
# - ./esphome/ks.yaml
- ./flaresolverr/ks.yaml
- ./forgejo/ks.yaml
- ./frigate/ks.yaml
- ./github-mirror/ks.yaml
- ./home-assistant/ks.yaml
- ./homebox/ks.yaml
- ./homepage/ks.yaml
- ./immich/ks.yaml
- ./it-tools/ks.yaml
- ./jellyfin/ks.yaml
- ./jellyseerr/ks.yaml
- ./lidarr/ks.yaml
- ./lldap/ks.yaml
- ./matter-server/ks.yaml
- ./mosquitto/ks.yaml
- ./music-assistant/ks.yaml
- ./n8n/ks.yaml
- ./node-red/ks.yaml
- ./openspeedtest/ks.yaml
- ./openwebui/ks.yaml
- ./paperless/ks.yaml
- ./prowlarr/ks.yaml
- ./qbittorrent/ks.yaml
- ./radarr/ks.yaml
- ./recyclarr/ks.yaml
- ./recommendarr/ks.yaml
- ./sabnzbd/ks.yaml
- ./searxng/ks.yaml
- ./sonarr/ks.yaml
- ./spoolman/ks.yaml
- ./zigbee/ks.yaml
- ./zipline/ks.yaml