---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zipline
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: zipline
  values:
    controllers:
      zipline:
        labels:
          postgres: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.1.0@sha256:3c54d39f19fdb82ed5b3f286450e4071133cc6025bd0e25856bc2c522f8fc030
            envFrom: &envFrom
              - secretRef:
                  name: zipline-secret
        containers:
          app:
            image:
              repository: ghcr.io/diced/zipline
              tag: trunk
            env:
              TZ: ${TIMEZONE}
              # Core config
              CORE_RETURN_HTTPS_URLS: true
              CORE_DEFAULT_DOMAIN: i.${SECRET_DOMAIN}
              # Datasources
              DATASOURCE_TYPE: local
              # Features
              INVITES_ENABLED: false
              FEATURES_ROBOTS_TXT: false
              FEATURES_USER_REGISTRATION: false
              FEATURES_OAUTH_REGISTRATION: true
              FEATURES_VERSION_CHECKING: false
              # OIDC
              OAUTH_OIDC_AUTHORIZE_URL: https://auth.${SECRET_DOMAIN}/api/oidc/authorization
              OAUTH_OIDC_USERINFO_URL: https://auth.${SECRET_DOMAIN}/api/oidc/userinfo
              OAUTH_OIDC_TOKEN_URL: https://auth.${SECRET_DOMAIN}/api/oidc/token
              # Files
              FILES_ROUTE: /u
              FILES_LENGTH: 6
              FILES_DEFAULT_FORMAT: "date"
              FILES_DISABLED_EXTENSIONS: "ps1,pdf,bat,exe,sh,fish"
              FILES_DEFAULT_DATE_FORMAT: "YYYY-MM-DD_HH-mm-ss"
              FILES_DEFAULT_EXPIRATION: ""
              FILES_REMOVE_GPS_METADATA: true
              DATASOURCE_LOCAL_DIRECTORY: "/uploads"
              # URLs
              URLS_ROUTE: /g
              URLS_LENGTH: 6
              # Website
              WEBSITE_TITLE: Zipline
            envFrom: *envFrom
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                memory: 256Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: &port 3000
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == any(200,401)"]
        hostnames: ["i.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      tmpfs:
        type: emptyDir
        advancedMounts:
          zipline:
            app:
              - path: /tmp
                subPath: tmp

      media:
        type: nfs
        server: f9-nas.internal
        path: /mnt/Data/Zipline
        globalMounts:
          - path: /uploads