---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webdev

components:
  - ../../components/alerts
  - ../../components/vars

resources:
  - ./namespace.yaml
  - ./debtmanager/ks.yaml
  - ./games-manager/ks.yaml
  - ./overlays/ks.yaml
  - ./ws-broadcast/ks.yaml