services:
  cups:
    container_name: "cups"
    devices:
      - "/dev/ricoh_printer:/dev/ricoh_printer"
    environment:
      TZ: "Europe/London"
    image: "ydkn/cups@sha256:76eb4fcc9bfce7573787938d9257cfced5dd21064559eae4ce112aa6a9d13ac2"
    network_mode: "bridge"
    ports:
      - "631:631/tcp"
    privileged: "true"
    restart: "unless-stopped"
    volumes:
      - "/mnt/apps-pool/appdata/cups:/etc/cups"
      - "/var/run/dbus:/var/run/dbus"
      - "/dev/bus/usb:/dev/bus/usb"
